version: '3'

services:
  selenium:
    container_name: coin-in-selenium
    image: iamrony777/raspberry:coin-in-selenium
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - logs:/app/logs:rw
      - cache:/app/cache:rw
      - screenshot:/app/screenshot:rw    
    network_mode: host
    deploy:
        resources:
          limits:
            cpus: '0.20'
            memory: 400M
    command: ["python3", "coin_in_selenium/app.py"]


volumes:
  logs:
  cache:
  screenshot:


