name: docker-build 

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */15 * *'
  push:
    branches:
      - "main"
jobs:
  qemu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.0.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      -
        run: echo "DOCKER_IMAGE_VERSION=$(date +'%d.%m.%Y')" >> $GITHUB_ENV       
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64, linux/arm64
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/coin-on-selenium:cache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/coin-on-selenium:cache,mode=max
          tags: ${{ secrets.DOCKER_USERNAME }}/coin-on-selenium:latest, ${{ secrets.DOCKER_USERNAME }}/coin-on-selenium:${{ env.DOCKER_IMAGE_VERSION }}